package chav1961.bt.installer.interfaces;

public enum StepType {
	WELCOME,
	SELECT_INSTALLATION_DIRECTORY,
	SELECT_REPOSITORY,
	SELECT_DATABASE_CONNECTION,
	REMOTE_DATA_DOWNLOAD,
	PREPARE_DATABASE_CONTENT,
	CONFIRM_INSTALLATION_PARAMETERS,
	INSTALLATION_PROCESSING,
	INSTALLATION_COMPLETE
}
