/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chav1961_bt_winsl_utils_JavaServiceLibrary */

#ifndef _Included_chav1961_bt_winsl_utils_JavaServiceLibrary
#define _Included_chav1961_bt_winsl_utils_JavaServiceLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chav1961_bt_winsl_utils_JavaServiceLibrary
 * Method:    installService
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chav1961_bt_winsl_utils_JavaServiceLibrary_installService
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     chav1961_bt_winsl_utils_JavaServiceLibrary
 * Method:    removeService
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chav1961_bt_winsl_utils_JavaServiceLibrary_removeService
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
