package chav1961.bt.installer.screens;

public enum ScreenType {
	WELCOME,
	DEFINE_DATABASE_CONNECTION,
	DEFINE_REPOSITORY_CONNECTION,
	DEFINE_SOURCE_CONTENT,
	DEFINE_TARGET_DIRECTORY,
	DEFINE_CHOISE,
	CALCULATE_CHOISE,
	PROCESSING_INSTALL,
	INSTALLATION_COMPLETED,
	INSTALLATION_FAILED;	
}
